// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmzlUbKYA-W7v0QBIAnif98qrAtpCU1TQ',
    appId: '1:224194309940:web:9d6eadb985db6df437bf61',
    messagingSenderId: '224194309940',
    projectId: 'flutter-app-e8368',
    authDomain: 'flutter-app-e8368.firebaseapp.com',
    storageBucket: 'flutter-app-e8368.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvduiMuKrtoloIq6tLYk-H5vGo3CsO6Eg',
    appId: '1:224194309940:android:a0237effa041338537bf61',
    messagingSenderId: '224194309940',
    projectId: 'flutter-app-e8368',
    storageBucket: 'flutter-app-e8368.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBafquqbO0Yny3ftVVfPO_l4LkO9QDy4No',
    appId: '1:224194309940:ios:fce7569d161b286637bf61',
    messagingSenderId: '224194309940',
    projectId: 'flutter-app-e8368',
    storageBucket: 'flutter-app-e8368.firebasestorage.app',
    iosBundleId: 'com.example.clothingStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBafquqbO0Yny3ftVVfPO_l4LkO9QDy4No',
    appId: '1:224194309940:ios:fce7569d161b286637bf61',
    messagingSenderId: '224194309940',
    projectId: 'flutter-app-e8368',
    storageBucket: 'flutter-app-e8368.firebasestorage.app',
    iosBundleId: 'com.example.clothingStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmzlUbKYA-W7v0QBIAnif98qrAtpCU1TQ',
    appId: '1:224194309940:web:b21b2d438a0a222437bf61',
    messagingSenderId: '224194309940',
    projectId: 'flutter-app-e8368',
    authDomain: 'flutter-app-e8368.firebaseapp.com',
    storageBucket: 'flutter-app-e8368.firebasestorage.app',
  );
}
