# Generated by Django 5.2 on 2025-04-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('men', "Men's Wear"), ('women', "Women's Wear"), ('shoes', 'Shoes')], default='men', max_length=20),
        ),
    ]
